### ISSUE TITLE
It doesn't work!

### ISSUE THREAD

**Issue by shen-changqing** [alphajc/meshctl#1]
Hello,
![图片](https://user-images.githubusercontent.com/23514413/128335598-b08d11b4-7003-44cb-8854-f78d6fdb40e3.png)
and internal/app/main.go createClientset() not used. Is there some code you didn't push?

**Comment by alphajc** [comment]
> Hello,
> ![图片](https://user-images.githubusercontent.com/23514413/128335598-b08d11b4-7003-44cb-8854-f78d6fdb40e3.png)
> and internal/app/main.go createClientset() not used. Is there some code you didn't push?

Oh....I'm sorry that cmd/meshctl/main.go was not pushed here.😂 It's my fault.

**Comment by shen-changqing** [comment]
Okay, I get it.
